name: zip
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=3.0.0=pyhd8ed1ab_1
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.7.15=h06a4308_0
  - certifi=2025.8.3=py310h06a4308_0
  - comm=0.2.2=pyhd8ed1ab_1
  - debugpy=1.8.11=py310h6a678d5_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_1
  - executing=2.2.0=pyhd8ed1ab_0
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=8.36.0=pyh907856f_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=7.3.4=pyhd8ed1ab_0
  - jupyter_core=5.7.2=pyh31011fe_1
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.0.17=h5eee18b_0
  - packaging=25.0=pyh29332c3_1
  - parso=0.8.4=pyhd8ed1ab_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.0=py310h06a4308_0
  - prompt-toolkit=3.0.51=pyha770c72_0
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - python=3.10.16=he870216_1
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.10=2_cp310
  - readline=8.2=h5eee18b_0
  - setuptools=75.8.0=py310h06a4308_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.14=h39e8969_0
  - tornado=6.1=py310h5764c6d_3
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.13.2=pyh29332c3_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.45.1=py310h06a4308_0
  - xz=5.6.4=h5eee18b_1
  - zeromq=4.3.5=h6a678d5_0
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - accelerate==1.6.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.18
      - aiosignal==1.3.2
      - airportsdata==20250224
      - annotated-types==0.7.0
      - anyio==4.9.0
      - astor==0.8.1
      - async-timeout==5.0.1
      - attrs==25.3.0
      - blake3==1.0.4
      - cachetools==5.5.2
      - charset-normalizer==3.4.1
      - click==8.1.8
      - cloudpickle==3.1.1
      - compressed-tensors==0.9.3
      - contourpy==1.3.2
      - cupy-cuda12x==13.4.1
      - cycler==0.12.1
      - datasets==3.5.0
      - deprecated==1.2.18
      - depyf==0.18.0
      - dill==0.3.8
      - diskcache==5.6.3
      - distro==1.9.0
      - dnspython==2.7.0
      - docker-pycreds==0.4.0
      - einops==0.8.1
      - email-validator==2.2.0
      - exceptiongroup==1.2.2
      - fastapi==0.115.12
      - fastapi-cli==0.0.7
      - fastrlock==0.8.3
      - filelock==3.18.0
      - flash-attn==2.7.4.post1
      - fonttools==4.58.0
      - frozenlist==1.6.0
      - fsspec==2024.12.0
      - gguf==0.16.2
      - gitdb==4.0.12
      - gitpython==3.1.44
      - googleapis-common-protos==1.70.0
      - grpcio==1.71.0
      - h11==0.14.0
      - hf-xet==1.0.3
      - httpcore==1.0.8
      - httptools==0.6.4
      - httpx==0.28.1
      - huggingface-hub==0.30.2
      - idna==3.10
      - importlib-metadata==8.0.0
      - interegular==0.3.3
      - jinja2==3.1.6
      - jiter==0.9.0
      - joblib==1.5.1
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - kiwisolver==1.4.8
      - lark==1.2.2
      - llguidance==0.7.18
      - llvmlite==0.44.0
      - lm-format-enforcer==0.10.11
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.3
      - mdurl==0.1.2
      - mistral-common==1.5.4
      - mpmath==1.3.0
      - msgpack==1.1.0
      - msgspec==0.19.0
      - multidict==6.4.3
      - multiprocess==0.70.16
      - networkx==3.4.2
      - ninja==1.11.1.4
      - numba==0.61.2
      - numpy==2.2.5
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - openai==1.75.0
      - opencv-python-headless==4.11.0.86
      - opentelemetry-api==1.26.0
      - opentelemetry-exporter-otlp==1.26.0
      - opentelemetry-exporter-otlp-proto-common==1.26.0
      - opentelemetry-exporter-otlp-proto-grpc==1.26.0
      - opentelemetry-exporter-otlp-proto-http==1.26.0
      - opentelemetry-proto==1.26.0
      - opentelemetry-sdk==1.26.0
      - opentelemetry-semantic-conventions==0.47b0
      - opentelemetry-semantic-conventions-ai==0.4.3
      - outlines==0.1.11
      - outlines-core==0.1.26
      - pandas==2.2.3
      - partial-json-parser==0.2.1.1.post5
      - pillow==11.2.1
      - platformdirs==4.3.7
      - prometheus-client==0.21.1
      - prometheus-fastapi-instrumentator==7.1.0
      - propcache==0.3.1
      - protobuf==4.25.6
      - psutil==7.0.0
      - py-cpuinfo==9.0.0
      - pyarrow==19.0.1
      - pycountry==24.6.1
      - pydantic==2.11.3
      - pydantic-core==2.33.1
      - pygments==2.19.1
      - pylatexenc==2.10
      - pyparsing==3.2.3
      - python-dotenv==1.1.0
      - python-json-logger==3.3.0
      - python-multipart==0.0.20
      - pytz==2025.2
      - pyyaml==6.0.2
      - pyzmq==26.4.0
      - ray==2.43.0
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.32.3
      - rich==14.0.0
      - rich-toolkit==0.14.1
      - rpds-py==0.24.0
      - safetensors==0.5.3
      - scikit-learn==1.7.1
      - scipy==1.15.2
      - sentencepiece==0.2.0
      - sentry-sdk==2.27.0
      - setproctitle==1.3.5
      - shellingham==1.5.4
      - smmap==5.0.2
      - sniffio==1.3.1
      - starlette==0.46.2
      - sympy==1.13.1
      - termcolor==3.2.0
      - threadpoolctl==3.6.0
      - tiktoken==0.9.0
      - tokenizers==0.21.1
      - torch==2.6.0
      - torchaudio==2.6.0
      - torchvision==0.21.0
      - tqdm==4.67.1
      - transformers==4.51.3
      - triton==3.2.0
      - typer==0.15.2
      - typing-inspection==0.4.0
      - tzdata==2025.2
      - urllib3==2.4.0
      - uvicorn==0.34.2
      - uvloop==0.21.0
      - vllm==0.8.5.post1
      - wandb==0.19.10
      - watchfiles==1.0.5
      - websockets==15.0.1
      - wrapt==1.17.2
      - xformers==0.0.29.post2
      - xgrammar==0.1.18
      - xxhash==3.5.0
      - yarl==1.20.0
      - zipp==3.21.0
prefix: /home/rohin/miniconda3/envs/zip
